repos:

  # black
  -   repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
        - id: black
          language_version: python3.8
          args:
            - --line-length=120

  # flake8
  -   repo: https://github.com/pycqa/flake8
      rev: 5.0.4
      hooks:
        - id: flake8
          args:
            - --ignore=E203
            - --max-line-length=120

  # isort
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --profile=black
          - --line-length=120